version: '3'
services:
    app:
        image: sappachok/node-web-app
        container_name: node-web-app
        restart: always
        ports:
            - 3000:3000
        links:
            - mongo
    mongo:
        image: mongo
        container_name: mongo
        ports:
            - 27017:27017